apiVersion: v1
kind: Service
metadata:
  name: access-url
spec:
  selector:
    app: access-url
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-url
  template:
    metadata:
      labels:
        app: access-url
    spec:
      containers:
      - name: access-url
        image: dotnsf/access_url
        ports:
        - containerPort: 8080
